GROQ_API_KEY = "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"
GITHUB_TOKEN = "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"
#JIRA_SERVER = "https://your-domain.atlassian.net"
#JIRA_USERNAME = "Hariniashini"
#JIRA_API_TOKEN = "ATATT3xFfGF0O9VjbXSUUjG6JeOR2UONvlWaj-S0M4uvJjR9YuhMtEWn0keDyNaQm1SkIcQfM0ooTbtekLJt_YqnrUFmj3te-oRz4HqS1VeS2S1mK_zpIDCg9mjvJWZMuR4fJCG7J378d9gZ1OvpDCBMxCwFdhR0mtDPw4V2Xy-fHj95kfyOBq0=BADC646E"